// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbxtflpiszcqgveckyjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZieHRmbHBpc3pjcWd2ZWNreWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODkwMDksImV4cCI6MjA2NzA2NTAwOX0.mjJCAoXs5CMFwtqTSg9_8AVQFFchqbi2VrzeGUgcah4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});